name: eccode_build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  install_dir: C:/eccodes
  conda_dir: C:/Miniconda/envs/build

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: "3.10"
          environment-file: environment.yaml
          activate-environment: build
      - name: Download ecCodes
        run: python download.py
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: |
          cd eccodes-2.32.1-Source
          mkdir build && cd build
          cmake ../CMakeLists.txt -G "NMake Makefiles" -D CMAKE_INSTALL_PREFIX=${{ env.install_dir }} -D CMAKE_BUILD_TYPE=Release -D ENABLE_FORTRAN=0 -D ENABLE_PYTHON=0 -D ENABLE_NETCDF=1 -D ENABLE_PNG=0 -D ENABLE_JPG=1 -D ENABLE_AEC=OFF -D OPENJPEG_INCLUDE_DIR=${{ env.conda_dir }}/Library/include/openjpeg-2.5 -D IEEE_LE=1 -D ENABLE_EXAMPLES=0 -D ENABLE_MEMFS=0 -D ENABLE_TESTS=0 -D ENABLE_EXTRA_TESTS=OFF
          nmake install
      - name: Packaging
        run: python post_process.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eccodes_bin
          path: eccodes-win-x64.zip