name: eccode_build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  install_dir: C:\eccodes
  conda_dir: C:\Miniconda

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          python-version: "3.10"
          environment-file: environment.yaml
          activate-environment: build
      - name: Download ecCodes
        run: python download.py
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: |
          python run_cmake.py
          nmake install
          copy "${{ env.conda_dir }}\Library\bin\openjp2.dll" "${{ env.install_dir }}\bin\"
          copy "${{ env.conda_dir }}\Library\bin\libpng16.dll" "${{ env.install_dir }}\bin\"
          copy "%${{ env.conda_dir }}\Library\bin\zlib.dll" "${{ env.install_dir }}\bin\"
          7z a eccodes-win-x64.zip "${{ env.install_dir }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: eccodes_bin
          path: eccodes-win-x64.zip